version: 2.1

orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@1.3.0

commands:
  install_deps:
    steps:
      - node/with-cache:
          cache-version: v1-all
          cache-key: package.json
          dir: ~/repo/node_modules
          use-strict-cache: true
          steps:
            - run: yarn install --pure-lockfile --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: '18'
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
#      - run: yarn lint:ci
      - run: yarn build
      - run: yarn export
      - persist_to_workspace:
          root: ~/repo
          paths:
            - out

  deploy:
    executor: aws-cli/default
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: ~/repo
      - run:
          name: deploy to s3
          command: |
            cd out
            aws s3 sync . s3://awsnews.info \
                --acl public-read \
                --exclude="*.map" \
                --cache-control="no-cache"

workflows:
  version: 2

  build_deploy:
    jobs:
      - build

      - deploy:
          context: AWS
          requires:
            - build
          filters:
            branches:
              only:
                - master
