version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.0

commands:
  install_deps:
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1-all
          cache-only-lockfile: true
          app-dir: ~/repo
          override-ci-command: >
            npx --yes retry-cli -n 5 -t 3000 --
            yarn install --pure-lockfile --ignore-scripts --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: '18.18.0'
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
#      - run: yarn lint:ci
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - out

  deploy:
    executor: aws-cli/default
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: ~/repo
      - run:
          name: deploy to s3
          command: |
            cd out
            aws s3 sync . s3://awsnews.info \
                --acl public-read \
                --exclude="*.map" \
                --cache-control="no-cache"

workflows:
  version: 2

  build_deploy:
    jobs:
      - build

      - deploy:
          context: AWS
          requires:
            - build
          filters:
            branches:
              only:
                - master
